jobs:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v3

      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    terraform-plan:
      name: 'Terraform plan'
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
 
       
        - name: 'Terraform Init'
          uses: hashicorp/terraform-github-actions@master
          with:
            tf_actions_version: 0.14.8
            tf_actions_subcommand: 'init'
            tf_actions_working_dir: "./terraform"
 
        - name: 'Terraform Validate'
          uses: hashicorp/terraform-github-actions@master
          with:
            tf_actions_version: 0.14.8
            tf_actions_subcommand: 'validate'
            tf_actions_working_dir: "./terraform"
         
        - name: 'Terraform Plan'
          uses: hashicorp/terraform-github-actions@master
          with:
            tf_actions_version: 0.14.8
            tf_actions_subcommand: 'plan'
            tf_actions_working_dir: "./terraform"
 
        - name: Terraform Apply
          if: github.ref == 'refs/heads/main'
          uses: hashicorp/terraform-github-actions@master
          with:
            tf_actions_version: 0.14.8
            tf_actions_subcommand: 'apply -auto-approve'
            tf_actions_working_dir: "./terraform"
